/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/player": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the player identified by the authenticated session. */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accepts one guess. Reusing the same request ID and direction is idempotent. */
        post: operations["createGuess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Quote: {
            /** @description Exact decimal USD price */
            price: string;
            tradeId: string;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            receivedAt: string;
            /** @enum {string} */
            source: "Coinbase";
        };
        Guess: {
            id: string;
            playerId: string;
            /** @enum {string} */
            direction: "up" | "down";
            entryPrice: string;
            entryTradeId: string;
            /** Format: date-time */
            entryPriceAt: string;
            /** Format: date-time */
            acceptedAt: string;
            /** Format: date-time */
            eligibleAt: string;
            /** @enum {string} */
            status: "pending" | "resolved";
            settlementPrice?: string;
            settlementTradeId?: string;
            /** Format: date-time */
            settlementPriceAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** @enum {integer} */
            delta?: 1 | -1;
        };
        PlayerState: {
            playerId: string;
            score: number;
            activeGuess: components["schemas"]["Guess"] | null;
            lastResult: components["schemas"]["Guess"] | null;
            /** Format: date-time */
            serverTime: string;
        };
    };
    responses: {
        /** @description Request failed. After a connection failure, fetch the current player state before retrying with the original request ID. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                    code: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPrice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh Coinbase BTC-USD quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative score and current round */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerState"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createGuess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    direction: "up" | "down";
                    /** Format: uuid */
                    requestId: string;
                };
            };
        };
        responses: {
            /** @description Updated player state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerState"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
